import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | Scandio",
  description: "Scandio Terms of Service. Informational directory and AI diagnostic tool for home maintenance.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-7xl items-center gap-4 px-4 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="size-4" />
            Back
          </Link>
          <Link href="/" className="flex items-center gap-2">
            <Image
              src="/logo.svg"
              alt="Scandio"
              width={28}
              height={28}
              className="h-7 w-7 shrink-0 rounded-lg"
            />
            <span className="font-semibold">Scandio</span>
          </Link>
        </div>
      </header>

      <main className="flex-1 px-4 py-12 sm:px-6 lg:px-8">
        <article className="mx-auto max-w-3xl">
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last Updated: February 2026</p>

          <div className="mt-10 space-y-8 text-foreground">
            <section>
              <h2 className="text-xl font-semibold">1. Nature of the Service</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                Scandio operates as an informational directory and diagnostic tool. The Service allows users to upload images and descriptions of home maintenance issues, receives an automated analysis generated by Artificial Intelligence (&quot;AI&quot;), and views a list of independent, third-party service providers (&quot;Professionals&quot;) located nearby.
              </p>
              <p className="mt-3 font-medium text-muted-foreground">
                Scandio is not a contractor, repair service, or certified professional. We do not perform home repairs, nor do we employ the Professionals listed on the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">2. AI Diagnostic Disclaimer (CRITICAL)</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                The diagnostic reports, part identification, repair steps, and estimated costs provided by Scandio are generated by artificial intelligence.
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6 text-muted-foreground">
                <li>
                  <strong className="text-foreground">Not Professional Advice:</strong> The AI output is for informational and educational purposes only. It does not constitute professional, certified, structural, plumbing, or electrical engineering advice.
                </li>
                <li>
                  <strong className="text-foreground">No Guarantee of Accuracy:</strong> While we strive for accuracy, the AI may misidentify issues, hallucinate, or provide incorrect cost estimates.
                </li>
                <li>
                  <strong className="text-foreground">Safety Warning:</strong> Home repairs—specifically electrical, structural, and high-pressure plumbing work—carry inherent risks of severe injury, death, or property damage. You must never attempt dangerous repairs based on Scandio&apos;s AI output. Always consult a certified, licensed Professional to verify the issue. Scandio accepts zero liability for any injury or damage resulting from reliance on the AI diagnosis.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold">3. Third-Party Professionals and Liability</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                Scandio aggregates publicly available data (including Google Maps and Google Reviews) to suggest local Professionals.
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6 text-muted-foreground">
                <li>
                  <strong className="text-foreground">No Endorsement or Vetting:</strong> We do not background check, license-verify, or guarantee the workmanship, pricing, or conduct of any Professional listed on the Service.
                </li>
                <li>
                  <strong className="text-foreground">Independent Contracts:</strong> If you choose to contact or hire a Professional found via Scandio, your contract is solely with that individual or company.
                </li>
                <li>
                  <strong className="text-foreground">Release of Liability:</strong> To the maximum extent permitted by South African law, Scandio shall not be liable for any damages, disputes, theft, poor workmanship, or financial loss arising from your engagement with a Professional.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold">4. User Obligations and Acceptable Use</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                When using the Service, you agree that you will not:
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6 text-muted-foreground">
                <li>Upload images containing personally identifiable information (e.g., faces, ID documents), illicit material, or content unrelated to home maintenance.</li>
                <li>Attempt to reverse-engineer, scrape, or overwhelm the Service&apos;s infrastructure.</li>
                <li>Use the Service for any illegal purpose.</li>
              </ul>
              <p className="mt-4 leading-relaxed text-muted-foreground">
                Scandio reserves the right to terminate your access to the Service at any time, without notice, for violating these terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">5. Intellectual Property</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                All code, design, branding, and text associated with the Service are the exclusive property of Scandio. The AI-generated text provided in response to your queries remains subject to the licensing terms of our underlying AI providers.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">6. Limitation of Liability</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                To the maximum extent permitted by applicable law, Scandio and its founders, affiliates, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the Service. The Service is provided on an &quot;AS-IS&quot; and &quot;AS-AVAILABLE&quot; basis without warranties of any kind.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">7. Governing Law</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                These Terms shall be governed by and construed in accordance with the laws of the Republic of South Africa. Any disputes shall be subject to the exclusive jurisdiction of the courts located in the Western Cape.
              </p>
            </section>
          </div>

          <div className="mt-12 border-t border-border pt-8">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="size-4" />
              Back to Home
            </Link>
          </div>
        </article>
      </main>
    </div>
  );
}
