/**
 * Phase 1 task 5 of the Diagnosis Architecture Hardening Plan.
 *
 * Builds the exact assembled system prompt + user-turn for each Phase 0
 * failure-baseline fixture (`p0-*.json`) and writes it to
 * `docs/prompt-snapshots/<fixture-name>.txt`.
 *
 * The snapshots are code-derivable — re-running this script regenerates the
 * canonical baseline. They are the empirical input to Phase 5's prompt
 * restructure: a before/after diff of system prompts is the cleanest evidence
 * that the rewrite preserved general principles and removed per-case patches.
 *
 * Run with:
 *   npx tsx scripts/capture-p0-prompt-snapshots.ts
 *
 * Does NOT make any Gemini calls — that's deferred to Phase 10 per the plan's
 * updated scope note.
 */

import fs from 'node:fs';
import path from 'node:path';
import {
    buildSystemInstruction,
    buildProseBaseInstruction,
} from '../src/features/diagnosis/prompts/composer';
import {
    buildTextOnlyFirstMessagePrompt,
    buildImageFirstMessagePrompt,
} from '../src/features/diagnosis/prompts/user-turn';
import { SERVICE_LABELS } from '../src/lib/services';
import type { PromptContext } from '../src/features/diagnosis/prompts/types';

const FIXTURES_DIR = path.resolve(__dirname, '..', 'src/__tests__/diagnostic-reasoning/fixtures');
const OUTPUT_DIR = path.resolve(__dirname, '..', 'docs/prompt-snapshots');

interface P0Fixture {
    name: string;
    trade: string;
    description: string;
    image_present?: boolean;
    image_quality?: string;
    hazard?: boolean;
}

function loadP0Fixtures(): P0Fixture[] {
    return fs
        .readdirSync(FIXTURES_DIR)
        .filter((f) => f.startsWith('p0-') && f.endsWith('.json'))
        .sort()
        .map((file) => JSON.parse(fs.readFileSync(path.join(FIXTURES_DIR, file), 'utf-8')) as P0Fixture);
}

function buildContext(fixture: P0Fixture): PromptContext {
    return {
        isFollowUp: false,
        hasUserContext: false,
        userSelectedTrade: null,
        isTextOnlyNoAttachments: fixture.image_present !== true,
        serviceListText: SERVICE_LABELS.join(', '),
        feedback: undefined,
        providers: undefined,
        previousDiagnosis: null,
        diagnosisRejected: false,
        isRefinementWithNewImages: false,
    };
}

function buildUserTurn(fixture: P0Fixture): string {
    const instructionPrefix = '';
    if (fixture.image_present === true) {
        return buildImageFirstMessagePrompt({
            instructionPrefix,
            userWordsPriority: `USER WORDS: ${JSON.stringify(fixture.description)}\n\n`,
            imageCount: 1,
            hasUserContext: false,
            userSelectedTrade: null,
        });
    }
    return buildTextOnlyFirstMessagePrompt({
        instructionPrefix,
        textQuery: fixture.description,
        hasUserContext: false,
        userSelectedTrade: null,
    });
}

function snapshotBody(fixture: P0Fixture, systemInstruction: string, proseInstruction: string, userTurn: string): string {
    const flagsTable = [
        ['isFollowUp', 'false'],
        ['hasUserContext', 'false'],
        ['isTextOnlyNoAttachments', String(fixture.image_present !== true)],
        ['previousDiagnosis', 'null'],
        ['diagnosisRejected', 'false'],
        ['isRefinementWithNewImages', 'false'],
    ];

    const flagsBlock = flagsTable
        .map(([k, v]) => `  ${k.padEnd(28)} ${v}`)
        .join('\n');

    return `# Prompt snapshot — ${fixture.name}

# This file is generated by scripts/capture-p0-prompt-snapshots.ts.
# Do not edit by hand. Re-run the script to regenerate.
#
# Source plan: docs/Diagnosis-Architecture-Hardening-Plan.md §Phase 1 task 5
# Fixture:     src/__tests__/diagnostic-reasoning/fixtures/${fixture.name}.json

## Fixture metadata

  trade                ${fixture.trade}
  image_present        ${fixture.image_present ?? false}
  image_quality        ${fixture.image_quality ?? 'n/a'}
  hazard               ${fixture.hazard ?? false}

## PromptContext flags (as composer.ts sees them)

${flagsBlock}

## User description (as submitted)

${fixture.description}

## ──────────────────────────────────────────────────────────────────────────
## buildSystemInstruction() — full system prompt sent to Gemini (Agent 2a path)
## ──────────────────────────────────────────────────────────────────────────

${systemInstruction}

## ──────────────────────────────────────────────────────────────────────────
## buildProseBaseInstruction() — stripped instruction used by Agent 2b
## ──────────────────────────────────────────────────────────────────────────

${proseInstruction}

## ──────────────────────────────────────────────────────────────────────────
## User turn (final user message text appended after the system instruction)
## ──────────────────────────────────────────────────────────────────────────

${userTurn}
`;
}

function main(): void {
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    const fixtures = loadP0Fixtures();
    if (fixtures.length === 0) {
        console.error('[snapshot] no p0-*.json fixtures found in', FIXTURES_DIR);
        process.exit(1);
    }

    for (const fixture of fixtures) {
        const ctx = buildContext(fixture);
        const systemInstruction = buildSystemInstruction(ctx);
        const proseInstruction = buildProseBaseInstruction(ctx);
        const userTurn = buildUserTurn(fixture);
        const body = snapshotBody(fixture, systemInstruction, proseInstruction, userTurn);
        const outPath = path.join(OUTPUT_DIR, `${fixture.name}.txt`);
        fs.writeFileSync(outPath, body, 'utf-8');
        console.warn(`[snapshot] wrote ${path.relative(process.cwd(), outPath)}`);
    }

    console.warn(`[snapshot] captured ${fixtures.length} prompt snapshots`);
}

main();
