import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    GEMINI_API_KEY: z.string().min(1).optional(),
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
    RESEND_API_KEY: z.string().min(1).optional(),
    RESEND_FROM: z.string().optional(),
    RESEND_FROM_NAME: z.string().optional(),
    RESEND_REPLY_TO: z.string().optional(),
    RESEND_ADMIN_EMAIL: z.string().optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
    ADMIN_PASSWORD: z.string().optional(),
    CRON_SECRET: z.string().optional(),
    GOOGLE_PLACES_API_KEY: z.string().optional(),
    GOOGLE_APPLICATION_CREDENTIALS: z.string().optional(),
    GOOGLE_SPEECH_CREDENTIALS_JSON: z.string().optional(),
    GOOGLE_MAPS_API_KEY: z.string().optional(),
    SEND_EMAIL_HOOK_SECRET: z.string().optional(),
    DISABLE_RATE_LIMIT: z.string().optional(),
    DISABLE_DIAGNOSIS_DAILY_QUOTA: z.string().optional(),
    MOCK_LLM: z.string().optional(),
    MOCK_PLACES: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_SUPABASE_URL: z.string().url().optional(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
    NEXT_PUBLIC_APP_URL: z.string().optional(),
    NEXT_PUBLIC_APP_ORIGIN: z.string().optional(),
    NEXT_PUBLIC_SITE_URL: z.string().optional(),
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: z.string().optional(),
    NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID: z.string().optional(),
    NEXT_PUBLIC_GOOGLE_PLACES_API_KEY: z.string().optional(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
    NEXT_PUBLIC_ENABLE_ANON_AUTH: z.string().optional(),
    NEXT_PUBLIC_DIAGNOSIS_MIN_CONFIDENCE: z.string().optional(),
    NEXT_PUBLIC_OPERATOR_LEGAL_NAME: z.string().optional(),
    NEXT_PUBLIC_OPERATOR_LEGAL_FORM: z.string().optional(),
    NEXT_PUBLIC_OPERATOR_PHYSICAL_ADDRESS: z.string().optional(),
    NEXT_PUBLIC_OPERATOR_POSTAL_ADDRESS: z.string().optional(),
    NEXT_PUBLIC_LEGAL_EMAIL: z.string().optional(),
    NEXT_PUBLIC_PRIVACY_EMAIL: z.string().optional(),
    NEXT_PUBLIC_INFORMATION_OFFICER_NAME: z.string().optional(),
    NEXT_PUBLIC_INFORMATION_OFFICER_EMAIL: z.string().optional(),
  },
  runtimeEnv: {
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM: process.env.RESEND_FROM,
    RESEND_FROM_NAME: process.env.RESEND_FROM_NAME,
    RESEND_REPLY_TO: process.env.RESEND_REPLY_TO,
    RESEND_ADMIN_EMAIL: process.env.RESEND_ADMIN_EMAIL,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    CRON_SECRET: process.env.CRON_SECRET,
    GOOGLE_PLACES_API_KEY: process.env.GOOGLE_PLACES_API_KEY,
    GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS,
    GOOGLE_SPEECH_CREDENTIALS_JSON: process.env.GOOGLE_SPEECH_CREDENTIALS_JSON,
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
    SEND_EMAIL_HOOK_SECRET: process.env.SEND_EMAIL_HOOK_SECRET,
    DISABLE_RATE_LIMIT: process.env.DISABLE_RATE_LIMIT,
    DISABLE_DIAGNOSIS_DAILY_QUOTA: process.env.DISABLE_DIAGNOSIS_DAILY_QUOTA,
    MOCK_LLM: process.env.MOCK_LLM,
    MOCK_PLACES: process.env.MOCK_PLACES,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_APP_ORIGIN: process.env.NEXT_PUBLIC_APP_ORIGIN,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
    NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID: process.env.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID,
    NEXT_PUBLIC_GOOGLE_PLACES_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_ENABLE_ANON_AUTH: process.env.NEXT_PUBLIC_ENABLE_ANON_AUTH,
    NEXT_PUBLIC_DIAGNOSIS_MIN_CONFIDENCE: process.env.NEXT_PUBLIC_DIAGNOSIS_MIN_CONFIDENCE,
    NEXT_PUBLIC_OPERATOR_LEGAL_NAME: process.env.NEXT_PUBLIC_OPERATOR_LEGAL_NAME,
    NEXT_PUBLIC_OPERATOR_LEGAL_FORM: process.env.NEXT_PUBLIC_OPERATOR_LEGAL_FORM,
    NEXT_PUBLIC_OPERATOR_PHYSICAL_ADDRESS: process.env.NEXT_PUBLIC_OPERATOR_PHYSICAL_ADDRESS,
    NEXT_PUBLIC_OPERATOR_POSTAL_ADDRESS: process.env.NEXT_PUBLIC_OPERATOR_POSTAL_ADDRESS,
    NEXT_PUBLIC_LEGAL_EMAIL: process.env.NEXT_PUBLIC_LEGAL_EMAIL,
    NEXT_PUBLIC_PRIVACY_EMAIL: process.env.NEXT_PUBLIC_PRIVACY_EMAIL,
    NEXT_PUBLIC_INFORMATION_OFFICER_NAME: process.env.NEXT_PUBLIC_INFORMATION_OFFICER_NAME,
    NEXT_PUBLIC_INFORMATION_OFFICER_EMAIL: process.env.NEXT_PUBLIC_INFORMATION_OFFICER_EMAIL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION || process.env.NODE_ENV === 'test',
});
